### ISSUE TITLE
Interleaved columns have values which are not in the source columns

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/corset#100]
To reproduce : 
[corset](https://github.com/Consensys/corset/commit/eba06497fe4ddfbd07141a4c422c540112179942)
[java](https://github.com/Consensys/besu-sequencer-plugins/pull/423/commits/031bd82661947f4632021df6cce0a23b23271a5a)
[constraints](https://github.com/Consensys/zkevm-constraints/pull/142/commits/454056e96808c596221ec719484036c7401676c2)

Test `successionOverlappingMstore()` in `MemoryTests.java`, `corset inspect` module `MMIO`, columns `VAL_ABC` and `VAL_ABC_NEW` have values which are not in the source columns (`VAL_A`, `VAL_B`, `VAL_C`, `VAL_A_NEW`, `VAL_B_NEW`, `VAL_C_NEW`)

**Comment by DavePearce** [comment]
Connected with #94 ?

**Comment by DavePearce** [comment]
@letypequividelespoubelles Its not really enough information for me to reproduce this error.  Can you include the trace that that you are running `corset check` with?  And, ideally, a bit more info about which row/column in that file is causing the problem.

**Comment by letypequividelespoubelles** [comment]
Maybe just a display issue of `corset inspect`, as (presumably) in #112 ?

**Comment by DavePearce** [comment]
Ok, recreation steps:

1. Checked out head of `feat/issue-142/mmio` (commit [cc64d1d](https://github.com/Consensys/linea-arithmetization/commit/cc64d1dab40b667f5d8205ac546e610a06eb7a2a)
2. Rebuild `zkevm-constraints/zkevm.bin`
3. Within the inspector select `mmio` module, and goto column 97 (?)

Screenshot attached.
![Uploading issue_100.png…]()

**Comment by DavePearce** [comment]
NOTES: column 48 has `1334440654591915542993625911497130241` for `VAL_ABC`

**Comment by DavePearce** [comment]
Ok, so this is starting to look like a presentation error.  The offending number does exist in the original trace file.  Specifically, we have this equivalence:

```
2668881309183831085987251822994260480 = 0x202020202020202020202020202020
```

So, the remaining question is why this is not being displayed in the correct form.

**Comment by DavePearce** [comment]
Ok, for reasons unknown, the column base is set to `Dec` for these columns rather than `Hex` (as for other columns).  I guess because they are computed columns?

**Comment by DavePearce** [comment]
It is possible to override the default base for an interleaved column like so:

```
(module test)
(defcolumns (A :byte) (B :byte))
(definterleaved (C :display :hex) (A B))
```

However, I think the default should be `Hex` anyway
