### ISSUE TITLE
`corset inspect` display `:display :bytes` in little endian order

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/corset#112]
I think it's just a display issue, but quite annoying while debugging.
In the following screenshot, `INPUT_1_{98} = LIMB_{98}`, `corset check` accepts the trace.
![image](https://github.com/Consensys/corset/assets/54240434/cded93b7-44cf-442b-a3d8-d304d5bfcdd6)
Columns are defined as follows:
```
(INPUT :i128 :display :bytes :array [2])
(LIMB :i128)
(ACC :i128 :display :bytes :array [2])
```

`INPUT_1` and `ACC_1` display bytes in wrong order

**Comment by DavePearce** [comment]
Ok, that looks pretty straightforward to fix.

**Comment by DavePearce** [comment]
Ok, minimal test case:

```
(module bytes)
(defcolumns (BS :i32 :display :bytes))
```
Along with trace data:
```
{"bytes": { "BS": [1,2,256,257,65536] } }
```
And command to recreate:
```
corset inspect --trace bytes.trace bytes.lisp
```

**Comment by DavePearce** [comment]
Ok, the fix for this is merged into `master`.
