### ISSUE TITLE
Restructure into Standard Rust Project Layout

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#118]
Currently, the project is configured in a slightly unusual fashion which doesn't quite fit the normal project layout.  In particular, this makes testing more awkward.  Notes:

* The project does not build a normal `lib`, which means that tests in the `tests/` directory cannot access it as a crate.
* Almost none of the API is exposed as public, meaning tests in the `tests/` directory (and other clients) cannot use the tool.
* Some modules are only included with the `main` binary, and not with the library.  Its unclear if they are left out for some reason.

These can all be changed relatively easily, though its not clear whether there was any specific reason for structuring like this.

**Comment by DavePearce** [comment]
@delehef Is there anything specific about the way the project is structured to note?  For example, you're specifically trying to keep the static / dynamic libraries as small as possible?

**Comment by delehef** [comment]
> Some modules are only included with the main binary, and not with the library. Its unclear if they are left out for some reason.

Because the lib only needs (needed?) what is required to expand traces, feel free to increase the public API surface.

> The project does not build a normal `lib`

What do you mean by a normal lib? It compiles a `.so`/`.dylib` for now.

**Comment by DavePearce** [comment]
Also, are both `cdylib` and `staticlib` needed?  I'm assuming one is linked on the Go side, so the other ... is not needed?

**Comment by DavePearce** [comment]
For now, I think this is not a priority :)
