### ISSUE TITLE
Unused Field `Column::shift` ?

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#131]
I believe the following field defined in `column.rs` is unused and could be safely removed:

```rust
pub struct Column {
    ...
    pub shift: i16,
```

I don't know what this field is supposed to do, but if it is deleted ... then `corset` still builds.  Therefore, I propose to remove this field altogether.

@delehef Any thoughts on this?

**Comment by delehef** [comment]
Yes, it can be safely removed.
