### ISSUE TITLE
Corset should automatically fill `spilling.toml`

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/corset#135]
We have a [file](https://github.com/Consensys/linea-arithmetization/blob/arith-dev/arithmetization/src/main/resources/spillings.toml) where we fill the spill over for all the module. It's now manually written, but it should be done automatically by Corset. 

I think the best moment to automatically regenerate it is when we generate the `Trace.java` : https://github.com/Consensys/linea-arithmetization/blob/arith-dev/gradle/trace-files.gradle

**Comment by DavePearce** [comment]
So, roughly, the spilling information tells us the maximum amount of shift used (in either a forwards or backwards direction).

**Comment by DavePearce** [comment]
@letypequividelespoubelles How do you normally generate the `Trace.java` file?  That is, what command do you use?

**Comment by letypequividelespoubelles** [comment]
>How do you normally generate the Trace.java file? That is, what command do you use?

you should coordinate with @powerslider as he's modifying it to have a common `*.java` with all shared constants 

> How is the spilling information used?

I don't know. I think it's used somehow when we expend the trace, but not sure.

**Comment by DavePearce** [comment]
Ok, the rough plan is:

1. Update `corset` with an option to trigger output from `debug -s` to be in `toml`.
2. Update the arithmetization build to use this (that's separate from this repository).

This issue will address (1) above, and I'll raise a separate issue for (2).

**Comment by DavePearce** [comment]
@letypequividelespoubelles @powerslider 

Ok, I have a branch with an initial version of this now.  There are some issues we need to resolve.  Here's how it looks:

```
> corset debug -s --toml zkevm.bin

# Automatically generated via `corset debug -s --toml`
[spillings]
       euc =    1
     binRT =    0
       stp =    4
       hub =    1
       mod =    7
       rom =    1
 rlpTxRcpt =    7
       mmu =   10
   ec_data =   11
      mmio =    1
       gas =    1
       trm =    7
instruction-decoder =    0
 hash_data =    0
       add =    1
   rlpAddr =    7
   shakira =    4
   logInfo =    5
    rlpTxn =    7
   logData =    1
     shfRT =    0
       shf =   15
       bin =   15
       mul =    8
       mxp =    3
    romLex =    1
blake2f_modexp_data =    0
   txnData =    7
       ext =    7
       wcp =   15
 hash_info =    0
       exp =    5
```

There are two specific issues to resolve:

1. (**Column Names**) The column names above differ from those currently in the [file](https://github.com/Consensys/linea-arithmetization/blob/arith-dev/arithmetization/src/main/resources/spillings.toml).  We can easily convert the above to upper case, no problem.  But that's not enough.  For example, we have `romLex` above which in the `spilling.toml` file is `ROM_LEX`.  We need to decide on a consistent naming for columns.
2. (**Missing Columns**) Some columns don't appear to be in the `zkevm.bin` file (e.g. `PRECOMPILE_SHA2_BLOCKS`, `BLOCK_TX`).  We just need to decide how to handle them.  It looks to me like we can just append these extras during the `gradle build` with them all assigned to `0`?

Thoughts?

**Comment by delehef** [comment]
(Those are not column but module names, but I'm 97% sure that's just a typo on your side)

1. Module names should be converted using the `ScreamingSnake` case of [convert_case](https://docs.rs/convert_case/0.6.0/convert_case/);
2. IIRC those are modules that are not yes constrained, so defaulting their spilling to 0 is the best solution.

**Comment by letypequividelespoubelles** [comment]
1) @powerslider can you handle this ?
2) TBH I don't understand why we have those modules in this files as those modules doesn't appear in the trace, they are just used to count ...

**Comment by DavePearce** [comment]
> Module names should be converted using the ScreamingSnake case of [convert_case](https://docs.rs/convert_case/0.6.0/convert_case/);

Yeah, I was thinking this might be the option.  But there are also a few odd differences, like `logInfo` versus `PUB_LOG_INFO` and also no `shfRT` ?

**Comment by DavePearce** [comment]
Ok, so output now looks like this:

```
> corset debug -s --toml zkevm.bin
# Automatically generated via `corset debug -s --toml`
[spillings]
    SHF_RT =    0
   ROM_LEX =    1
       BIN =   15
       MMU =   10
  TXN_DATA =    7
   EC_DATA =   11
INSTRUCTION_DECODER =    0
       SHF =   15
       GAS =    1
RLP_TX_RCPT =    7
       MXP =    3
BLAKE_2_F_MODEXP_DATA =    0
      MMIO =    1
       HUB =    1
       EXT =    7
       MUL =    8
  LOG_DATA =    1
 HASH_DATA =    0
       MOD =    7
       ROM =    1
    BIN_RT =    0
       EXP =    5
   SHAKIRA =    4
       WCP =   15
  LOG_INFO =    5
       TRM =    7
  RLP_ADDR =    7
       EUC =    1
   RLP_TXN =    7
 HASH_INFO =    0
       ADD =    1
       STP =    4
```
There are still differences from the original file which need to be resolved.  However, I think this issue is resolved and I'll now move it over to the [arithmetisation repo](https://github.com/Consensys/linea-arithmetization).
