### ISSUE TITLE
Understanding the Initial Padding Row

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#143]
For a simple example like this:

```
(defcolumns A B)
(defconstraint test1 () (eq! A B))
```

With a trace say:

```json
{ "<prelude>": {"A": [123], "B": [123] } }
```

Then after trace expansion we have this:

```json
{ "<prelude>": {"A": [0,123], "B": [0,123] } }
```

So, _I'm wondering why at least one padding row is always added_.   My current ideas are:

1. (`Sorting`).  This is necessary to ensure that any sorted column always contains `0` and, thus, arbitrary padding can be added.  That still doesn't feel right because columns sorted in descending order could not have `0` at the beginning?

Hmmmm, that's all I've got for now.  @delehef Any comments on this?

**Comment by DavePearce** [comment]
Here's a permutation example:

```
(defcolumns A)
(defpermutation (B) ((- A)))
(defconstraint test1 () (eq! A B))
```

Then, for this input trace:

```
{ "<prelude>": {"A": [123,456] } }
```

We get this expanded trace:

```
{"columns":{
"B":{
  "values":["0x0456","0x0123","0x00"],
  "padding_strategy": {"action": "prepend", "value": "456"}
},
"A":{
  "values":["0x00","0x0123","0x0456"],
  "padding_strategy": {"action": "prepend", "value": "0"}
}
...
```

So, that makes sense, but then it actually indicates we don't need the `0` for padding the sorted column as we can just pick the least value from the column.

**Comment by delehef** [comment]
> So, I'm wondering why at least one padding row is always added

IIRC, to be sure that constraints are working even with the padding added.

Thinking about it, I assume this row could be prepended only for `corset check`.

**Comment by DavePearce** [comment]
> Thinking about it, I assume this row could be prepended only for `corset check`.

I am imagining that it might make sense to have an option where we can enumerate different amounts of padding being added.  For example, we can quickly check that a trace is accepted (or rejected) even when arbitrary padding between `0` and e.g. `16` rows is added.

**Comment by letypequividelespoubelles** [comment]
I think we require to always have one padding rows so that you can always be the receptacle of an empty lookup without failing. Module which are not the target of a lookup could leave without a padding row, but does it exist ?

**Comment by DavePearce** [comment]
> you can always be the receptacle of an empty lookup without failing

Right, because if padding rows are added for columns being used to lookup into another module ... then they will be zero.  Interesting.  I guess another solution is to fill them with e.g. values from the first row to resolve this.

**Comment by DavePearce** [comment]
I guess also that, on any given, row lookups are not always actually used.  For example, looking up into the wcp module is only needed for rows representing instructions which use e.g. `LT`, etc.  For an instruction which doesn't use `wcp` functionality, then I guess we leave the columns at `0`.

This is helping.  Its interesting.

**Comment by letypequividelespoubelles** [comment]
> Well, I meant setting the padding value. But, to be honest, I don't think this sounds like a great idea just to save one row of zeros!

I really don't get what you mean, we really need an empty row in modules to make the lookup working

**Comment by delehef** [comment]
The thing is lookups are typically over multiple columns. So you would need to add a new line ${Y_i}$ coming from module Y to all the columns ${X_i}$ of module X, all the while _not breaking X own constraints_; which, notwithstanding complexity, is probably impossible generally speaking.

**Comment by DavePearce** [comment]
> The thing is lookups are typically over multiple columns of two modules, each with their own inner constraints.

Hmmmm, yeah fair enough --- it would be hard for the trace expander to do the right thing. I guess the advantage of padding with zeros is that its a known quantity.  The user knows to expect it, and can work around it.  🤔

Anyway, I'm going to close this now --- I think we spent enough time on it!!

**Comment by letypequividelespoubelles** [comment]
and plus, most of the time, the lookup will come with a "selector" (a bit column), so the lookup is not X into Y, but `selector * X` into `Y`, so even if you don't have a 0 in X columns, you will have one in `slector * X`
