### ISSUE TITLE
Print perspective (shorthand) in corset output

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/corset#170]
When debugging the HUB in corset I run into the issue that there are different perspectives with homonymous columns:

<img width="500" alt="image" src="https://github.com/Consensys/corset/assets/38285177/afb086a2-932a-467b-909f-b4a1fec314a0">

In this case we have the "shared" column CONTEXT_NUMBER and the "context" column CONTEXT_NUMBER (`context/CONTEXT_NUMBER` in Lisp.) Context (no pun intended) is sufficient to recognize which is which (the context/CONTEXT_NUMBER is only present on context rows i.e. whenever PEEK_AT_CONTEXT = 1) but it would be nice to have

- perspective shorthand in front of the columns output by corset check, similarly to what is present in corset inspect
- optionally (e.g. via `--perspectives`) graying out of the cells that pertains to some `perspective/COLUMN` when the corresponding perspective flag is off

So for example
```bash
         CONTEXT_NUMBER              2  2  2  2  
         PEEK_AT_CONTEXT             0  1  1  0
         PEEK_AT_STACK               1  0  0  1
con/     CONTEXT_NUMBER              ⋅  5  5  ⋅
stk/     STACK_ITEM_VALUE_HI_2      1f  ⋅  ⋅  1
```

**Comment by DavePearce** [comment]
> perspective shorthand in front of the columns output by corset check, similarly to what is present in corset inspect

Ok, well that seems reasonable enough to add.
