### ISSUE TITLE
Bug with Expansion of `Norm(e)` Expressions

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#171]
Minimal lisp for reproduction:

```lisp
(module bug)

(defcolumns MAX (OLI :binary))

(defconstraint test ()
  (if-eq OLI 1 (vanishes! MAX)))
```

And this trace:

```
{"bug": {   
    "MAX": [0,0,7,7,7,7,7,7],
    "OLI": [0,0,0,0,0,0,0,0]
}}
```

Then, `corset check` passes, and also with `-eeeN`.  But, `-eeeeN` gives the following error:

```
bug.test failed:
     1  2  3  4  5  
MAX  0  0  7  7  7  
OLI  0  0  0  0  0  

(* (- 1 (eq! x val) (.- OLI<0> 1)) → 8444461749428370424248824938781546531375899335154063827935233455917409239040→ 2
 MAX<7>) → 14

Error: while checking test.json

Caused by:
    constraints failed: bug.test
```

**NOTES:** removing the `:binary` constraint on `OLI` and it passes.  Conclusion: a problem with translation of `:binary` constraints and/or corresponding trace expansion.

@powerslider FYI --- minimal test illustrating the problem.

**Comment by DavePearce** [comment]
```
(* (- 1 (.- OLI<0> 1)) → ... → 2
 MAX<7>) → 14
```

This suggest some kind of order of execution issue?  We've got `1 - - 1` which is `1+1` and gives `2` ?

Without the `:binary` column type, the translation is actually different giving a different path.

**Comment by DavePearce** [comment]
The problem here is that, whilst `OLI` is `:binary`, the expression `OLI - 1` is *not* `:binary`.

**Comment by DavePearce** [comment]
Expansion occurs in `transformer/inverses.rs`:

```rust
 pub(crate) fn do_normalize(
        &mut self,
        get_module: &dyn Fn(&HashSet<ColumnRef>) -> String,
        new_cols: &mut Vec<(Handle, Node)>,
    ) {
    ...
     else if arg.t().is_binary() {
        // No need for a normalised column if its already binary.
        *self = arg.clone();
      }
}
```

**Comment by DavePearce** [comment]
So, two different expansions of our constraint where the first passes the trace, whilst the second rejects it: 

```lisp
(defconstraint test ()
  (* (vanishes! (- 1 (~ (- OLI 1)))) (vanishes! MAX)))
```

```lisp
(defconstraint test ()
  (* (vanishes! (- 1 (~ (-. OLI 1)))) (vanishes! MAX)))
```

**Comment by DavePearce** [comment]
So, the issue boils down to the function `Type.maxed()` which is called indirectly from `Intrinsic.typing`:

```
pub fn typing(&self, argtype: &[Type]) -> Result<Type> {
        Ok(match self {
            ...
            Intrinsic::Add | Intrinsic::Sub | Intrinsic::Neg => {
                // Boolean is a corner case, as it is not stable under these operations
                let max_t = max_type(argtype)?;
                match max_t.m().rm() {
                    RawMagma::Binary => max_t.with_raw_magma(RawMagma::Native),
                    _ => max_t,
                }
            }
            Intrinsic::VectorAdd | Intrinsic::VectorSub | Intrinsic::VectorMul => {
                super::max_type(argtype.iter())?
            }
```
We can see a specific exception has been given for the `binary` case for the non-vector intrinsics which is not repeated for the vector intrinsics.

However, overall, the problem for me here is that using `max_type` in this context does not make sense.  In essence, `max_type` is forming a join operator of sorts where e.g. `binary ⊔ binary = binary`.  But, this doesn't hold for `Add` or `Sub`.

**Comment by DavePearce** [comment]
A list of actual inputs / outputs from `maxed`:
```
∅ ⊔ [𝟙] => [𝟙]
∅ ⊔ 𝟙 => 𝟙
[𝟙] ⊔ [𝟙] => [𝟙]
𝟙 ⊔ [𝟙] => [𝟙]
𝟙 ⊔ [𝟙->𝔹] => [𝟙->𝔹]
𝟙 ⊔ 𝟙->𝔹 => 𝟙->𝔹
𝟙 ⊔ [𝟙->𝕃] => [𝟙->𝕃]
𝟙 ⊔ 𝟙->𝕃 => 𝟙->𝕃
[𝟙] ⊔ [𝔽->𝔹] => [𝔽->𝔹]
[𝟙] ⊔ [𝔽] => [𝔽]
[𝟙] ⊔ 𝔽 => 𝔽
𝟙 ⊔ [𝔽] => [𝔽]
𝟙 ⊔ 𝔽 => 𝔽
𝟙 ⊔ [i128] => [i128]
[𝟙] ⊔ [i32] => [i32]
∅ ⊔ [𝟠] => [𝟠]
[𝟠] ⊔ [𝔽] => [𝔽]
[𝟠] ⊔ 𝔽 => 𝔽
[𝔽] ⊔ [𝟙] => [𝔽]
𝔽 ⊔ [𝟙] => 𝔽
𝔽 ⊔ [𝟠] => 𝔽
∅ ⊔ [𝔽->𝔹] => [𝔽->𝔹]
[𝔽->𝔹] ⊔ [𝔽->𝔹] => [𝔽->𝔹]
[𝔽->𝔹] ⊔ [𝔽] => [𝔽->𝔹]
[𝔽->𝔹] ⊔ 𝔽 => 𝔽->𝔹
∅ ⊔ [𝔽] => [𝔽]
∅ ⊔ 𝔽 => 𝔽
𝔽 ⊔ 𝔽->𝔹 => 𝔽->𝔹
[𝔽] ⊔ [𝔽] => [𝔽]
[𝔽] ⊔ 𝔽 => [𝔽]
𝔽 ⊔ [𝔽] => [𝔽]
𝔽 ⊔ 𝔽 => 𝔽
𝔽 ⊔ [i128] => i128
[𝔽] ⊔ [i32] => [i32]
𝔽 ⊔ [i5] => i5
𝔽 ⊔ [i64] => i64
𝔽 ⊔ i64 => i64
[i128] ⊔ [𝟙] => [i128]
∅ ⊔ [i128] => [i128]
[i128] ⊔ i64 => [i128]
[i24] ⊔ 𝟙 => [i24]
∅ ⊔ [i24] => [i24]
[i24] ⊔ [i24] => [i24]
∅ ⊔ [i32] => [i32]
[i32] ⊔ [i32] => [i32]
[i48] ⊔ 𝔽 => i48
∅ ⊔ [i48] => [i48]
[i5] ⊔ 𝔽 => i5
∅ ⊔ [i5] => [i5]
∅ ⊔ [i64] => [i64]
[i64] ⊔ [i64] => [i64]
[i64] ⊔ i64 => [i64]
[i8] ⊔ 𝔽 => i8
∅ ⊔ [i8] => [i8]
[i8] ⊔ [i8] => [i8]
```
Do all of these make sense?  Some looking odd ones to me:

- `𝔽 ⊔ [𝟙] => 𝔽`
- `[i5] ⊔ 𝔽 => i5`
- `𝔽 ⊔ i64 => i64`
- `𝔽 ⊔ 𝔽->𝔹 => 𝔽->𝔹`

**Comment by DavePearce** [comment]
**NOTES**: `max_type` is used in five locations:

- In `generator.rs` to construct the type of a `List`
- In `node.rs` to determine the type of a `List`
- In `types.rs` as above to type arithmetic intrinsics and `List`.

**Comment by delehef** [comment]
> 𝔽 ⊔ [𝟙] => 𝔽

Looks like this should be [𝔽]

> [i5] ⊔ 𝔽 => i5

Same

> 𝔽 ⊔ i64 => i64

Should be 𝔽 I guess

> 𝔽 ⊔ 𝔽->𝔹 => 𝔽->𝔹

Depends on whether this is + or × I suppose.

All in all, I was already starting to doubt the idea of the general `max` functions, and I'm more and more convinced that this is actually a bad idea and that expression typing should be delegated to `Intrinsic`-specific functions.

**Comment by DavePearce** [comment]
> All in all, I was already starting to doubt the idea of the general max functions, and I'm more and more convinced that this is actually a bad idea and that expression typing should be delegated to Intrinsic-specific functions.

Well, the general idea of a "join" operator like this for type inference is pretty normal.  Sometimes its the least upper bound, sometimes its the greatest lower bound.  Depends what you're trying to do.  So, I don't think the idea is crazy at all.  But, it has to be used correctly I guess.

Part of the issue is that the system is not sufficiently expressive for everything we want.  In particular, it doesn't consider ranges.  That is, where we represent the type of a variable by the range of values it can hold e.g. `0..1` for an `i1`, `0..255` for a `i8`, etc.  With that information, you can write four useful operators:

* `T1 ⊔ T2 = T3` is essentially set union where e.g. `0..1 ⊔ 1..2 = 0..2`, etc This makes sense in situations where we want one type that conservatively approximates a set of types.  E.g. for `(if c e1 e2)` it makes sense to use this to compute the type of the overall expression as anything that can be in either `e1` or `e2`.
* `T1 ⊓ T2 = T3` is essentially set intersection where `0..1 ⊓ 1..2 = 1..1`.  I'm not sure where exactly we could use this.
* `T1 × T2 = T3` this is the product operator where e.g. `0..1 × 0..1 = 0..1` and `0..2 × 0..3 = 0..6`, etc.
* `T1 + T2 = T3` this is the sum operator where e.g. `0..1 + 0..1 = 0..2` and `0..2 + 0..3 = 0..5`, etc.

Anyway, I'm rambling on here.  I guess the point is, we could make this work.  I've done this before (see paper [here](https://whileydave.com/publications/pea15_seus/) and Rust implementation [here](https://github.com/Consensys/EvmIL/blob/main/src/util/interval.rs)).  The condition is one aspect which is specific to this situation, and I didn't fully understand what makes sense here.  It seems to me that part of the issue is typing code which is already written.
