### ISSUE TITLE
Invalid `define.go` for complex Guard

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#176]
Minimal example:

```
(module test)
(defcolumns X (BYTE :array[0:1]))
(defconstraint test
    (:guard (reduce + (for k [1:1] [BYTE k])))
  (vanishes! X))
```

This produces the following `define.go`:

```go
package define

import (
	_ "embed"

	"github.com/consensys/zkevm-monorepo/prover/symbolic"
)

func ZkEVMDefine(build *Builder) {
	//
	// Corset-computed columns
	//
	test__BYTE_0 := build.RegisterCommit("test.BYTE_0", build.Settings.Traces.Test)
	test__BYTE_1 := build.RegisterCommit("test.BYTE_1", build.Settings.Traces.Test)
	test__X := build.RegisterCommit("test.X", build.Settings.Traces.Test)

        ...

	build.GlobalConstraint("test.test", test__BYTE_1.AsVariable(),.Mul(test__X.AsVariable()))
}
```

Note the last line contains a syntax error: `... AsVariable(),.Mul( ...`

**Comment by DavePearce** [comment]
So, the issue is with this section of code:

```rust
fn render_expression(cs: &ConstraintSet, e: &Node) -> String {
    match e.e() {
       ...
        Expression::List(constraints) => constraints
            .iter()
            .map(|e| render_expression(cs, e))
            .map(|mut x| {
                if let Some(true) = x.chars().last().map(|c| c != ',') {
                    x.push(',');
                }
                x
            })
            .collect::<Vec<_>>()
            .join("\n"),
```

In essence, we have a `List` with a single item which is causing the problem.

**Comment by delehef** [comment]
> `(+ (for k [0:2] [BYTE k]))`

This should fail at the verification of the arguments to `+`, that accepts multiple arguments, but not an argument that is a list.

In this case, the appropriate guard expression would be `(reduce + (for k [0:2] [BYTE k]))`

**Comment by DavePearce** [comment]
> This should fail at the verification of the arguments to +, that accepts multiple arguments, but not an argument that is a list.

Yeah, that makes sense.  I will look into doing that tomorrow :)

**Comment by DavePearce** [comment]
Ok, merged in fix for the initial example (which uses a `reduce`).  Have opened #191 for case when `reduce` omitted.
