### ISSUE TITLE
Column names are truncated in `corset inspect` when filtering columns 

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/corset#212]
How to reproduce:
Open a .lt trace with `corset -inspect`.
Filter columns (using `f` terminal command)
Results: some columns name are not full (the STACL_ITEM_VALUE_HIGH_#) in this case:
![image](https://github.com/Consensys/corset/assets/54240434/d8583888-95cc-468a-b9dd-f8f486b8a841)

Note: column names are well displayed when no filter, so this is a low priority bug

**Comment by DavePearce** [comment]
Hey @letypequividelespoubelles A few quick questions:

- What version of Corset are you using?
- Is this behaviour new?  As in, it was previously displaying properly and is now not?

**Comment by letypequividelespoubelles** [comment]
1) last corset release v0.9.12
2) no idea

Precision, it seems the issue is only when the longest column is declared as an `array`, and so the last character (its array index) is forgotten. If we filter with longer columns it appears back.
Maybe putting a `+2` instead of `+1` in https://github.com/Consensys/corset/blob/d7b4ee5c7b9cba5e1273f496e2b3074394a56287/src/inspect/mod.rs#L135 would solve ?
