### ISSUE TITLE
Optionally make values invisible in multiplexed columns when not in the right perspective

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/corset#215]
When `corset inspect`'ing a trace we see all the values present in a "real" underlying column (e.g. `A xor B xor C xor D`) regardless of the perspective (the values are greyed out but still visible.) Since these values have no meaning along the rows of a "virtual column" associated with a perspective (and in any case we have little influence over what columns get grouped together outside of their underlying type IIUC) it would be nice to have the option to fully mask them and instead display 1 or 2 blank space characters per irrelevant cell.

Besides greater legibility this would also make representations more compact, especially when filtering for "virtual columns" from a given perspective. The presence of large unrelated values in the underlying "real column" can lead to fewer rows being displayed on screen.

**Comment by DavePearce** [comment]
Hey @OlivierBBB, ok have implemented this feature.  Its merged into `master` so you should try it out and see whether it's what you wanted.  Some minor points:

* By default inactive perspectives are "blanked".  That is, as described above, values in those columns are empty.
* You can toggle this behaviour for each module being displayed using the `p` key.  This is shown as the `[p]erspectives` item on the command bar at the bottom.

Anyway, it seems to work and column widths are recalculated after toggling, etc.

**Comment by OlivierBBB** [comment]
Thank you @DavePearce 🙂 I just checked it out with @letypequividelespoubelles and it's beautiful, especially since switching is so simple !
