### ISSUE TITLE
Different Behavior for Expansion and Native Flag Combinations

### ISSUE THREAD

**Issue by LukiMueller** [Consensys/corset#219]
Hello,
While experimenting with the `corset` tool I have encountered a strange behavior for following code snippet:

test.lisp
~~~lisp
(defcolumns X)

(defconstraint Constraint ()
    (let ((tmp-var (neq! (if (is-zero 1)  X X) X)))
        (~or!
            (~and! 1 tmp-var)
            (~and! 1 tmp-var)
        )
    )
)
~~~

test.trace:
~~~json
{ "<prelude>": { "X": [0] }}
~~~

Executing a `corset check` with different expansion levels yield different results:

**Executions that trigger a constraint violation:**
~~~
$> corset check test.lisp --trace test.trace

Error: while checking test.trace

Caused by:
    constraints failed: Constraint
~~~

~~~
$> corset check test.lisp --trace test.trace -N

Error: while checking test.trace

Caused by:
    constraints failed: Constraint
~~~

**Executions that do not trigger a constraint violation:**
~~~
$> corset check test.lisp --trace test.trace -e
~~~
~~~
$> corset check test.lisp --trace test.trace -eN
~~~
~~~
$> corset check test.lisp --trace test.trace -eeee
~~~

**Executions that trigger a rust panic:**
~~~
$> corset check test.lisp --trace test.trace -eeeeN

thread 'main' panicked at src/transformer/inverses.rs:42:70:
called `Result::unwrap()` on an `Err` value: InvalidValue("field element", BigInt(17827233559389713581281927431961797741912996166142033254001995846146059988359617266106055091980460976682379710737573254447789329466495203024905374269441))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~~~

**Corset Version**
~~~
$> corset --version
corset 9.7.12 d7b4ee5 SIMD JSON parsing unavailable
~~~

**Comment by DavePearce** [comment]
So, I can recreate this behaviour.  I agree that it is a bug in `corset`.  Slightly simplified version:

```
(defcolumns X)

(defconstraint Constraint ()
  (or!
   (~and! 1 (neq! (if (is-zero 1)  X X) X))
   (~and! 1 (neq! (if (is-zero 1)  X X) X))
   )
)
```
**NOTE** `(~or!` becomes `(or!` here.

This still fails with `-N`, and passes with e.g. `-eeeN`.  However, it doesn't crash with `-eeeeN`.  Therefore, it seems that `~or!` is related to the crash and is perhaps a separate issue.

**Comment by DavePearce** [comment]
Simplest version I can find:

```
(defcolumns X)

(defconstraint Constraint ()
   (neq! (if (is-zero 1)  X X) X)
)
```

**Comment by DavePearce** [comment]
And, now I find this:

```
(defcolumns X)

(defconstraint Constraint ()
   (vanishes! 1)
)
```
This is different (but presumably related) as it doesn't fail on either `-N` or `-eeeN`, etc

**Comment by DavePearce** [comment]
Ok, so I understand what's going on now.  Since the expression being checked is a constant, then `corset` bails as it cannot find the necessary column height for evaluation.  This is actually reported as a warning (use `-v` to see this).

**Comment by OlivierBBB** [comment]
BTW: we very sparingly (if at all) use `let` and even more sparingly (AFAIK) `~and!` / `~or!` etc ... in the actual constraint system. In case these are at fault.
