### ISSUE TITLE
Wrong Evaluation of Normalized Loobean And

### ISSUE THREAD

**Issue by LukiMueller** [Consensys/corset#244]
I found following equivalence violations for the evaluation of the `~and!` operator.

**test.json**
~~~lisp
(defcolumns ST)

;; F
(defconstraint constraint-01 () (if-not-zero ST (vanishes! 1)))

;; F && F
(defconstraint constraint-02 () (if-not-zero ST (~and! 1 1)))

;; (0 == 1) && F
(defconstraint constraint-03 () (if-not-zero ST (~and! (eq! 0 1) 1))) ;; <--- does not fail

;; F && (0 == 1)
(defconstraint constraint-04 () (if-not-zero ST (~and! 1 (eq! 0 1))))  ;; <--- does not fail

;; (0 == 1) && (0 == 1)
(defconstraint constraint-05 () (if-not-zero ST (~and! (eq! 0 1) (eq! 0 1))))

;; ((0 == 1) && (0 == 1)) && F
(defconstraint constraint-06 () (if-not-zero ST (~and! (~and! (eq! 0 1) (eq! 0 1)) 1)))

;; F && ((0 == 1) && (0 == 1))
(defconstraint constraint-07 () (if-not-zero ST (~and! 1 (~and! (eq! 0 1) (eq! 0 1)))))  ;; <--- does not fail

;; ((0 == 1) && (0 == 1)) && (0 == 1)
(defconstraint constraint-08 () (if-not-zero ST (~and! (~and! (eq! 0 1) (eq! 0 1)) (eq! 0 1))))  ;; <--- does not fail

;; (0 == 1) && ((0 == 1) && (0 == 1))
(defconstraint constraint-09 () (if-not-zero ST (~and! (eq! 0 1) (~and! (eq! 0 1) (eq! 0 1)))))  ;; <--- does not fail

;; (((0 == 1) && (0 == 1)) && T) && (0 == 1)
(defconstraint constraint-10 () (if-not-zero ST (~and! (~and! (eq! 0 1) 0) (eq! 0 1))))  ;; <--- does not fail

;; (0 == 1) && ((0 == 1) && T)
(defconstraint constraint-11 () (if-not-zero ST (~and! (eq! 0 1) (~and! (eq! 0 1) 0))))  ;; <--- does not fail
~~~

**trace.json**
~~~json
{
    "<prelude>": { "ST": [ 1 ] }
}
~~~

**execution output**
~~~
> corset check test.lisp --trace trace.json -Neeee

Error: while checking trace.json

Caused by:
    constraints failed: constraint-06, constraint-07, constraint-02, constraint-01, constraint-05
~~~

`corset` is able to find the violation for `01`, `02`, `05`, `06`, `07` but `passes` for the rest.
I observe the same issue also for different flags, e.g.  `-N`, `-e`, `-eeee`, none, etc.

**Comment by DavePearce** [comment]
This maybe related to #83.  Specifically, this `(~and! (eq! 0 1) 1)` is in principle not well typed.  Roughly, we have `(eq! X Y)` reduces to `(- X Y)`.  The definition of `eq!` in the standard library helps us here:

```
(defpurefun ((eq! :@loob :force) x y) (~>> (-. x y)))
```

This does not indicate that it returns `binary@loob` which is needed for `and!` to be sound (see #83).  Exactly what the `~>>` operator is supposed to do in this case is not clear to me, but it currently compiles as a NO-OP.

@delehef What is `~>>` supposed to indicate here?

**Comment by delehef** [comment]
> What is ~>> supposed to indicate here?

A word-wise normalization, which is identical to `~` here as the field-agnosticity mechanism is not enabled.

**Comment by DavePearce** [comment]
Looking at this evaluation:

- `(defconstraint constraint-03 () (if-not-zero ST (~and! (eq! 0 1) 1)))`
- => `(defconstraint constraint-03 () (if-not-zero ST (~and! (~ (- 0 1)) 1)))`
- => `(defconstraint constraint-03 () (if-not-zero ST (~and! 1 1)))`

So, to me that should be equivalent to the original.

**Comment by DavePearce** [comment]
The problem is with `~>>`.  Here's is the minimal example:

```
(defpurefun ((and! :@loob) a b) (+ a b))
(defpurefun ((~and! :binary@loob) a b) (~ (and! a b)))
(defpurefun ((eq! :@loob :force) x y) (~>> (- x y)))

(defcolumns (ST :binary@bool))

;; F && F
(defconstraint constraint-02 () (if ST (~and! 1 1)))

;; (0 == 1) && F
(defconstraint constraint-03 () (if ST (~and! (eq! 0 1) 1)))
```

Changing `~>>` to `~` gives the expected outcome.

**Comment by DavePearce** [comment]
The obvious solution here is to remove all uses of `~>>` from the standard library, and then disable parsing for it.  Since this functionality is not in play, I don't see any value in trying to fix it.

**Comment by DavePearce** [comment]
For reference, we have these two outcome for:

```
corset --no-stdlib debug -ceeeeN --auto-constraints=nhood,sorts issue244.lisp
```

gives either:

```
ST
```

or
```
0
```

**Comment by DavePearce** [comment]
Minimal test case now:

```
(defcolumns (ST))
(defconstraint test () (~ (- ST 1)))
```

This compiles down to either this (incorrect):

```
test ::= ST - 1
```

or this (correct):

```
test :=
(ST - 1) * C/INV[(- ST 1)]

NORM[(- ST 1)] :=
|(- ST 1)| == (- ST 1) × C/INV[(- ST 1)]
(- ST 1)×(1 - (- ST 1)×C/INV[(- ST 1)]) = 0
C/INV[(- ST 1)]×(1 - (- ST 1)×C/INV[(- ST 1)]) = 0
```

**Comment by DavePearce** [comment]
This behaviour is the same as per `v9.7.10` --- so its not my refactoring which introduced the problem.  I think the intention is that the example should actually fail with an exception.

**Comment by DavePearce** [comment]
The problem seems to be in function `apply_builtin` of `compiler/generator.rs`:

```
        Builtin::NormFlat => {
            if traversed_args[0].is_exocolumn() {
                todo!("{}", traversed_args[0].pretty())
            } else {
                Ok(Some(traversed_args[0].clone()))
            }
        }
```

To be honest, I think we should disable all exo-related stuff.

**Comment by DavePearce** [comment]
@LukiMueller Note that [this PR](https://github.com/Consensys/corset/pull/269) effectively undoes the fix put through for resolving this issue.  In essence we now:

* Implement `(eq! X Y)` as `(- X Y)` (this is essentially what we originally had)
* But now remove `and!` / `or` / `all!` and `any`.

This means problematic scenarios such as `(and! (eq! 0 1) (eq! 1 0))` are eliminated by construction.
