### ISSUE TITLE
fix: new `Trace.java` files cannot be generated in the hub branch

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/corset#251]
Issue faced by
- @lorenzogentile404
- @OlivierBBB

**Comment by OlivierBBB** [comment]
@powerslider @DavePearce Should this issue live in the https://github.com/Consensys/linea-tracer repo instead ?

**Comment by DavePearce** [comment]
@lorenzogentile404 You need to give more details of what exactly the problem is.

**Comment by lorenzogentile404** [comment]
![Screenshot 2024-08-23 at 10 20 42](https://github.com/user-attachments/assets/a8b0a3f1-3788-4957-9dcb-8f6f89e40d74)

**Comment by DavePearce** [comment]
@lorenzogentile404 How did you fix this?
