### ISSUE TITLE
Setting column size factor manually

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/corset#266]
Certain helper columns in the HUB only exist in the "interleaved and permuted domain" but arise neither as the row permutation of other columns nor as the interleaving of existing columns from the HUB. We ought to be able to declare them with a size parameter (here: 4.)

Currently when attempting to declare them we can't tell corset that they ought to be considered as columns 4x as long as standard HUB module columns. We get the following error:

<img width="1343" alt="image" src="https://github.com/user-attachments/assets/d23b40af-9d20-42eb-8d63-0fcf589d4ea4">

**Comment by DavePearce** [comment]
Options for syntax:

```
(defcolumns (X :length@2))
```

or

```
(defcolumns (X :height@2))
```

**Comment by DavePearce** [comment]
Minimal example to illustrate:

```
(defcolumns X Y (A :length@2))
(definterleaved (Z) (X Y))
(defconstraint tmp () (vanishes! (- A Z)))
```
