### ISSUE TITLE
possibility to filter by perspective with corset inspect

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/corset#280]
When corset inspect, we can now filter by columns eg "ABS_" will display only all columns that contains "*ABS_*" in their name. It would be nice to filter by perspective too, eg filter by "acc STAMP" would display all account perspective columns + all columns with STAMP in their name

**Comment by DavePearce** [comment]
@letypequividelespoubelles How do you feel about regular expressions?  We can make the search string a regular expression which would mean something like `acc | STAMP` would do it.
