### ISSUE TITLE
Constraints containing only a debug one

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/corset#284]
Currently Corset seems to do not accept constraints containing only a debug one, such as the following:

```
(defconstraint stamp-increments ()
    (debug (any! (will-remain-constant! STAMP) (will-inc! STAMP 1))))
```

Our current work around, is adding an always-satisfied constraint, such as:

```
(defconstraint stamp-increments ()
  (begin 
    (vanishes! 0)
    (debug (any! (will-remain-constant! STAMP) (will-inc! STAMP 1)))))
```

We would like Corset to accept such as the first one.

**Comment by DavePearce** [comment]
Hmmm, so it seems that `corset check` accepts such constraints without problem.  I guess the error must be arising in some other function, such as the `besu` command?

**Comment by DavePearce** [comment]
So, here's my initial test:

```
(defcolumns X Y)

(defconstraint other ()
  (vanishes! X))

(defconstraint test ()
  (debug (vanishes! Y)))
```

This seems fine with the commands `corset check --debug`, `corset compile --debug` and `corset besu --debug`.  The only relevant aspect seems to be that at least one real constraint is required.

@lorenzogentile404 Can you give me more details on where this arises exactly?

**Comment by DavePearce** [comment]
Ok, eventually I found this:

```
(defcolumns STAMP)

(defconstraint first-stamp (:domain {0}) (vanishes! STAMP))

(defconstraint stamp-increments ()
  (begin
    (debug (any! (will-remain-constant! STAMP) (will-inc! STAMP 1)))))
```

The original example given above does not fail.  However, this example does fail with the following command line:

```
corset compile --out debug.bin debug.lisp
```

The error reported is:

```
Error: compiling debug.lisp

Caused by:
    0: at line 6: (begin...
    1: expected at least 1 argument, but received 0
```

The error indicates an empty `(begin ...)` list is not accepted by `corset`.  However, curiously, running the same file with this command succeeds:

```
corset compile --debug --out debug.bin debug.lisp
```
