### ISSUE TITLE
Displaying negative numbers for debugging

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/corset#302]
Here is an example of a trace that fails with an underflow: rather than evaluating to 0 a certain difference presumably evaluates to some (small ?) negative integer.

<img width="1579" alt="image" src="https://github.com/user-attachments/assets/864b48f0-b63b-4655-8aa7-1d91d14a5ba0">

Would it be possible to _display_ these values as negative integers ? Knowing whether the value is on the order of
- `-32006` (static cost of CREATE's + memory expansion)
- `-951796` (1/64 of `leftoverGas - upfrontGasCost)`
- `-60914953` (`leftoverGas`)

Would be useful information when debugging (these are all relevant values in this example)

**Comment by DavePearce** [comment]
It seems to me that showing negative values makes for something which is way more readable!!

**Comment by DavePearce** [comment]
Example for testing:

```lisp
(module m1)
(defcolumns X Y Z)
(defconstraint c1 () (eq! Z (- X Y)))
```
Here's a simple trace which holds:
```
{ "m1": { "X": [0], "Y": [1], "Z": [8444461749428370424248824938781546531375899335154063827935233455917409239040] } }
```
Then, using the inspector we get this output:
```
    0   1
 X  0x0 0x0
 Y  0x0 0x1
 Z  0x0 0x12ab655e9a2ca55660b44d1e5c37b00159aa76fed00000010a11800000000000
```

Where, in fact, for `Z` we might prefer a negative number.

**Comment by DavePearce** [comment]
After the update, for this trace:

```
{ "m1": { "X": [0,1], "Y": [1,3], "Z": [84444617494283704242488249387815465313758993351540638279352334\
55917409239040,8444461749428370424248824938781546531375899335154063827935233455917409239039] } }
```
We now get:

```
    0   1   2
 X  0   0   1
 Y  0   1   3
 Z  0   -1  -2
```
