### ISSUE TITLE
Add if-false and if-true as aliases to stdlib

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/corset#70]
The goal is to turn:

```
(if-not-zero (raw_hi_part_is_zero)
             (vanishes! (lead_log))
             (if-not-zero (ebs_cutoff_leq_16)
                          (vanishes! (lead_log))
                          (eq! (lead_log)
                               (* 8 (- (ebs_cutoff) 16)))))
```

into this:

```
(if-true (raw_hi_part_is_zero)
             (vanishes! (lead_log))
             (if-true (ebs_cutoff_leq_16)
                          (vanishes! (lead_log))
                          (eq! (lead_log)
                               (* 8 (- (ebs_cutoff) 16)))))
```
Ideally, Corset should throw an exception if the condition is not a boolean.

**Comment by delehef** [comment]
`raw_hi_part_is_zero` should just be a `bool`-returning function, then you can just use the standard `if`.

**Comment by OlivierBBB** [comment]
In this particular use case (and in many others) the function is just a pointer to a column that can contain values of any type --- boolean or not. Can we still make the function return a boolean ? 

BTW: Whenever the value returned by this function is used (i.e not killed by a precondition failing) it's return value will be a boolean.

**Comment by delehef** [comment]
IIUC, it should then simply be:

```
(if (vanishes! THE_COLUMN)
    (then...))
```
