### ISSUE TITLE
Show Constraints Arising from `@prove` ?

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#92]
_(see also #91)_

A question I'm unsure about is whether or not columns marked with `@prove` should generate additional constraints.  For example:

```lisp
(defcolumns (BIN :byte@prove))
(defconstraint eg2 () (vanishes! (- 1 BIN)))
```
Generates the following (according to `corset debug`):
```
eg2 :=
1 - BIN
```
Likewise, this generates the same constraints:
```
(defcolumns (BIN :binary@prove))
(defconstraint eg2 () (vanishes! (- 1 BIN)))
```

My understanding previously is that `binary@prove` should result in a specific binary constraint being added (e.g. `BIN * (1-BIN)`).  Likewise, I assumed that `byte@prove` would result in a range constraint or a lookup.  So, it seems odd that there is nothing being added in both cases above.

**Comment by DavePearce** [comment]
Also, must check the effect of perspectives.  Specifically, if `B` belongs to a perspective then `B :binary@prove` should generate something like `P * B * (B - 1)`.

**Comment by DavePearce** [comment]
So, for the example above, looking at the generated `go` output from `wizard-iop` gives this:

```
func ZkEVMDefine(build *Builder) {
        //
        // Corset-computed columns
        //
        test__A := build.RegisterCommit("test.A", build.Settings.Traces.Test)
        test__B := build.RegisterCommit("test.B", build.Settings.Traces.Test)
        test__C := build.RegisterCommit("test.C", build.Settings.Traces.Test)


        //
        // Interleaved columns
        //


        //
        // Constraints
        //
        build.GlobalConstraint("test.A-binarity", test__A.AsVariable().Mul(symbolic.NewConstant("1").Sub(test__A.AsVariable())))
        build.GlobalConstraint("test.test2", symbolic.NewConstant("1").Sub(test__A.AsVariable()).Mul(test__B.AsVariable().Sub(test__C.AsVariable())))
}
```

**Comment by DavePearce** [comment]
Considering perspectives now.  This is my test example:

```
(module test)
(defcolumns (A :binary@prove) B C (P :binary@prove))
(defperspective perp
    P
  ((D:binary@prove)))

(defconstraint test2 (:perspective perp) (eq! (if (vanishes! A) B) C))
```

**Comment by delehef** [comment]
Do not forget the `--auto-constraints=nhood` when calling `corset debug` to see the auto-generated type constraints.
