### ISSUE TITLE
Deterministic Builds

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#94]
For reasons unknown (though probably connected with Rayon), corset builds are currently non-deterministic.  That is, generating the same `bin` file twice leads to different output.  This makes it very hard indeed to track changes between builds, and needs to be resolved ASAP.

This issue manifests itself in two ways:

* **(File Size)** the resulting files have different sizes.

* **(Constraint Ordering)** the resulting constraints have different orderings.  For example, in the generated `go` file we can sometimes get this:
```
add := Interleave(add_H, add__BYTE_1, add__BYTE_2)
```
whilst other times we get this:
```
add := Interleave(add_H, add__BYTE_2, add__BYTE_1)
```
Its unclear to me whether these are equivalent.

**Comment by DavePearce** [comment]
Note running with `corset -t 1 ...` does not resolve this issue.  It also could mean that, in order to safely generate the `bin` and `go` files they need to be done at the same time?

**Comment by delehef** [comment]
> It also could mean that, in order to safely generate the bin and go files they need to be done at the same time?

It's probably stemming from the fact that `HashMap` iteration is not guaranteed to be reproducible; `BTreeMap` _e.g._ is.

**Comment by DavePearce** [comment]
Yeah, that is one of the normal reasons for non-determinism.  I guess the question is whether or not the difference in the output above actually matter?

**Comment by DavePearce** [comment]
**UPDATE:** Something very unexpected is going on here.  Given this input file:
**permute.lisp**
```
(module test)
(defcolumns A)
(defpermutation (B) ((+ A)))
(defconstraint test () (vanishes! (+ A B)))
```

**permute.trace**
```
{"test": { "A": [1] } }
```

Then, I had this session:

```
djp@Workstation:~/projects/Corset$ corset convert --format csv --trace permute.trace permute.lisp
djp@Workstation:~/projects/Corset$ cat trace.csv_test 
A,B
0,0x1
djp@Workstation:~/projects/Corset$ corset convert --format csv --trace permute.trace permute.lisp
djp@Workstation:~/projects/Corset$ cat trace.csv_test 
A,B
0x1,0
```

Notice how the ordering can change between consecutive runs.
